"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Banana.py']
DATA_FILES = ['banana_desk.icns', 'alipay20.png', 'embeding.icns', 
'wechat10.png', 'webarchiver.command', 'tarfolder.txt', 'choose.txt', 'alipay5.png', 
'wechat5.png', 'alipay50.png', 'with_embeddings3.csv', 'with_embeddings2.csv', 'banana.icns', 
'api.txt', 'wechat50.png', 'alipay10.png', 'banana.png', 'wechat20.png', 'with_embeddings.csv', 
'output.txt', 'which.txt', 'chatwith.txt', 'temperature.txt', 'maxtokens.txt']
OPTIONS = {'iconfile': 'banana_desk.icns',
           'packages': ['PyQt6', 'openai', 'markdown2', 'codecs', 'transformers', 'pyperclip', 'requests',
            'bs4', 'numpy', 'pandas', 'html2text', 'jieba', 'glob', 'signal', 'subprocess', 'urllib3',
            'logging', 'httpx', 'asyncio'],
           'plist': {
            'CFBundleShortVersionString': '0.0.7',
            'LSUIElement': True,
            },
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    author='Ryan-the-hito',
    version='0.0.7'
)
